payload:
  # NAME: Tools
  - DOMAIN-SUFFIX,keyshot.com
  - DOMAIN-SUFFIX,macwk.cn

  # NAME: News
  - DOMAIN-SUFFIX,rfi.fr
  - DOMAIN-SUFFIX,dw.com
  - DOMAIN-SUFFIX,wordpress.com

  # NAME: For Fun / Porn
  - DOMAIN-SUFFIX,missav.ws
  - DOMAIN-SUFFIX,pornhub.com

  # NAME: Anime
  - DOMAIN-SUFFIX,zodgame.xyz # ZodGame论坛，主营i社游戏，国内可访问但较慢
  - DOMAIN-SUFFIX,www.acgkkk.com # ACGUUU资源站
  - DOMAIN-SUFFIX,www.gtloli.eu.org # 哥特动漫王国
